### ISSUE TITLE
Fetch select records from DB

### ISSUE THREAD

**Issue by trvslhlt** [tuna42na/baby-namr#3]
baby-namr-api fetches all name records before filtering them. This is an issue because loading too many records into memory causes Heroku to raise an error. Further it takes unnecessarily long to fetch all of the records. 

Instead, the rails app should selectively fetch records.

**Comment by cwkarwisch** [comment]
This bug has been addressed in [this PR](https://github.com/cwkarwisch/baby_namer_api/pull/7).

The change has been merged and deployed, so the app is now responding in a timely manner to requests for filtered results.
