### ISSUE TITLE
Benchmark api response time as a function of query parameters

### ISSUE THREAD

**Issue by trvslhlt** [tuna42na/baby-namr#9]
We want to know how long it takes to get a response from the service so we know what needs to be improved. And once improvements are made, show that they have made a difference.

**Comment by cwkarwisch** [comment]
The benchmark tests were added with this [PR](https://github.com/cwkarwisch/baby_namer_api/pull/10). Median response times went down from 3.5s and 4.5s (the first two times the tests were run) to 662ms and 402ms (tests were again ran twice) after indexes were added to the name, sex, popularity and year columns in the `names` table.
